title: Hello, world! The pnpdot.com user manual is provided.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # "/flexible-jekyll" the subpath of your site, e.g. /blog
url: "http://pnpsoft.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: PnPSoft # add your name David Freeman
author-img: pnpsoft.png # add your photo
about-author: 피앤피소프트입니다. 아주 작은 Tip으로 커다란 변화를 가져올 수 있습니다.{It is PnPSoft. A very small Tip can make a big difference.} # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: artemsheludko # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: pnpdot@pnpdot.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
